// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResponsePacket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Acorle.Models {

  /// <summary>Holder for reflection information generated from ResponsePacket.proto</summary>
  public static partial class ResponsePacketReflection {

    #region Descriptor
    /// <summary>File descriptor for ResponsePacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponsePacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRSZXNwb25zZVBhY2tldC5wcm90bxINQWNvcmxlLk1vZGVscxoSSGVhZGVy",
            "S1ZQYWlyLnByb3RvIsMECg5SZXNwb25zZVBhY2tldBINCgVtYWdpYxgBIAEo",
            "DBI8CgRjb2RlGAIgASgOMi4uQWNvcmxlLk1vZGVscy5SZXNwb25zZVBhY2tl",
            "dC5SZXNwb25zZUNvZGVUeXBlEiwKB2hlYWRlcnMYAyADKAsyGy5BY29ybGUu",
            "TW9kZWxzLkhlYWRlcktWUGFpchIMCgRkYXRhGAQgASgMIqcDChBSZXNwb25z",
            "ZUNvZGVUeXBlEgYKAk9LEAASFQoQU0VSVkVSX0VYQ0VQVElPThDoBxIOCglO",
            "T1RfRk9VTkQQ6QcSDgoJRk9SQklEREVOEOoHEhAKC0JBRF9HQVRFV0FZEOsH",
            "EhAKC0JBRF9SRVFVRVNUEOwHEhgKE1NFUlZJQ0VfVU5BVkFJTEFCTEUQ7QcS",
            "FwoSTUVUSE9EX05PVF9BTExPV0VEEO4HEhEKDElOVkFMSURfQk9EWRDvBxIV",
            "ChBSUENfSU5WQUxJRF9aT05FENAPEhkKFFJQQ19PUEVSQVRJT05fRkFJTEVE",
            "ENEPEhIKDVJQQ19SRUdfTElNSVQQ0g8SFwoSUlBDX1JFU1BPTlNFX0VSUk9S",
            "ENMPEhoKFVJQQ19SRVNQT05TRV9USU1FRE9VVBDUDxIaChVSUENfTkVUV09S",
            "S19FWENFUFRJT04Q1Q8SGQoUUlBDX0NPTkZJR19OT1RfRk9VTkQQ1g8SFQoQ",
            "U1ZDX0lOVkFMSURfWk9ORRC4FxIhChxTVkNfTk9UX0ZPVU5EX09SX1VOQVZB",
            "SUxBQkxFELkXYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Acorle.Models.HeaderKVPairReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Acorle.Models.ResponsePacket), global::Acorle.Models.ResponsePacket.Parser, new[]{ "Magic", "Code", "Headers", "Data" }, null, new[]{ typeof(global::Acorle.Models.ResponsePacket.Types.ResponseCodeType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 响应 
  /// </summary>
  public sealed partial class ResponsePacket : pb::IMessage<ResponsePacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResponsePacket> _parser = new pb::MessageParser<ResponsePacket>(() => new ResponsePacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResponsePacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Acorle.Models.ResponsePacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponsePacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponsePacket(ResponsePacket other) : this() {
      magic_ = other.magic_;
      code_ = other.code_;
      headers_ = other.headers_.Clone();
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponsePacket Clone() {
      return new ResponsePacket(this);
    }

    /// <summary>Field number for the "magic" field.</summary>
    public const int MagicFieldNumber = 1;
    private pb::ByteString magic_ = pb::ByteString.Empty;
    /// <summary>
    /// 包特征，用于占位及表示是己方协议 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Magic {
      get { return magic_; }
      set {
        magic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 2;
    private global::Acorle.Models.ResponsePacket.Types.ResponseCodeType code_ = global::Acorle.Models.ResponsePacket.Types.ResponseCodeType.Ok;
    /// <summary>
    /// 响应状态码 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Acorle.Models.ResponsePacket.Types.ResponseCodeType Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "headers" field.</summary>
    public const int HeadersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Acorle.Models.HeaderKVPair> _repeated_headers_codec
        = pb::FieldCodec.ForMessage(26, global::Acorle.Models.HeaderKVPair.Parser);
    private readonly pbc::RepeatedField<global::Acorle.Models.HeaderKVPair> headers_ = new pbc::RepeatedField<global::Acorle.Models.HeaderKVPair>();
    /// <summary>
    /// 响应头 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Acorle.Models.HeaderKVPair> Headers {
      get { return headers_; }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 4;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// 响应数据 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResponsePacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResponsePacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Magic != other.Magic) return false;
      if (Code != other.Code) return false;
      if(!headers_.Equals(other.headers_)) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Magic.Length != 0) hash ^= Magic.GetHashCode();
      if (Code != global::Acorle.Models.ResponsePacket.Types.ResponseCodeType.Ok) hash ^= Code.GetHashCode();
      hash ^= headers_.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Magic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Magic);
      }
      if (Code != global::Acorle.Models.ResponsePacket.Types.ResponseCodeType.Ok) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Code);
      }
      headers_.WriteTo(output, _repeated_headers_codec);
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Magic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Magic);
      }
      if (Code != global::Acorle.Models.ResponsePacket.Types.ResponseCodeType.Ok) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Code);
      }
      headers_.WriteTo(ref output, _repeated_headers_codec);
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Magic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Magic);
      }
      if (Code != global::Acorle.Models.ResponsePacket.Types.ResponseCodeType.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      size += headers_.CalculateSize(_repeated_headers_codec);
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResponsePacket other) {
      if (other == null) {
        return;
      }
      if (other.Magic.Length != 0) {
        Magic = other.Magic;
      }
      if (other.Code != global::Acorle.Models.ResponsePacket.Types.ResponseCodeType.Ok) {
        Code = other.Code;
      }
      headers_.Add(other.headers_);
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Magic = input.ReadBytes();
            break;
          }
          case 16: {
            Code = (global::Acorle.Models.ResponsePacket.Types.ResponseCodeType) input.ReadEnum();
            break;
          }
          case 26: {
            headers_.AddEntriesFrom(input, _repeated_headers_codec);
            break;
          }
          case 34: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Magic = input.ReadBytes();
            break;
          }
          case 16: {
            Code = (global::Acorle.Models.ResponsePacket.Types.ResponseCodeType) input.ReadEnum();
            break;
          }
          case 26: {
            headers_.AddEntriesFrom(ref input, _repeated_headers_codec);
            break;
          }
          case 34: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ResponsePacket message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResponseCodeType {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("SERVER_EXCEPTION")] ServerException = 1000,
        [pbr::OriginalName("NOT_FOUND")] NotFound = 1001,
        [pbr::OriginalName("FORBIDDEN")] Forbidden = 1002,
        [pbr::OriginalName("BAD_GATEWAY")] BadGateway = 1003,
        [pbr::OriginalName("BAD_REQUEST")] BadRequest = 1004,
        [pbr::OriginalName("SERVICE_UNAVAILABLE")] ServiceUnavailable = 1005,
        [pbr::OriginalName("METHOD_NOT_ALLOWED")] MethodNotAllowed = 1006,
        [pbr::OriginalName("INVALID_BODY")] InvalidBody = 1007,
        [pbr::OriginalName("RPC_INVALID_ZONE")] RpcInvalidZone = 2000,
        [pbr::OriginalName("RPC_OPERATION_FAILED")] RpcOperationFailed = 2001,
        [pbr::OriginalName("RPC_REG_LIMIT")] RpcRegLimit = 2002,
        [pbr::OriginalName("RPC_RESPONSE_ERROR")] RpcResponseError = 2003,
        [pbr::OriginalName("RPC_RESPONSE_TIMEDOUT")] RpcResponseTimedout = 2004,
        [pbr::OriginalName("RPC_NETWORK_EXCEPTION")] RpcNetworkException = 2005,
        [pbr::OriginalName("RPC_CONFIG_NOT_FOUND")] RpcConfigNotFound = 2006,
        [pbr::OriginalName("SVC_INVALID_ZONE")] SvcInvalidZone = 3000,
        [pbr::OriginalName("SVC_NOT_FOUND_OR_UNAVAILABLE")] SvcNotFoundOrUnavailable = 3001,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
