// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServiceProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Acorle.Models {

  /// <summary>Holder for reflection information generated from ServiceProto.proto</summary>
  public static partial class ServiceProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for ServiceProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJTZXJ2aWNlUHJvdG8ucHJvdG8SDUFjb3JsZS5Nb2RlbHMi6QEKDFNlcnZp",
            "Y2VQcm90bxI8CghzZXJ2aWNlcxgBIAMoCzIqLkFjb3JsZS5Nb2RlbHMuU2Vy",
            "dmljZVByb3RvLlNlcnZpY2VNZXNzYWdlGpoBCg5TZXJ2aWNlTWVzc2FnZRIM",
            "CgRoYXNoGAEgASgJEgsKA2tleRgCIAEoCRIMCgRuYW1lGAMgASgJEgsKA3Vy",
            "bBgEIAEoCRIOCgZ3ZWlnaHQYBSABKAUSEQoJaXNQcml2YXRlGAYgASgIEhYK",
            "DmFkZGVkVGltZXN0YW1wGAcgASgDEhcKD2V4cGlyZVRpbWVzdGFtcBgIIAEo",
            "A2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Acorle.Models.ServiceProto), global::Acorle.Models.ServiceProto.Parser, new[]{ "Services" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Acorle.Models.ServiceProto.Types.ServiceMessage), global::Acorle.Models.ServiceProto.Types.ServiceMessage.Parser, new[]{ "Hash", "Key", "Name", "Url", "Weight", "IsPrivate", "AddedTimestamp", "ExpireTimestamp" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ServiceProto : pb::IMessage<ServiceProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServiceProto> _parser = new pb::MessageParser<ServiceProto>(() => new ServiceProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServiceProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Acorle.Models.ServiceProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceProto(ServiceProto other) : this() {
      services_ = other.services_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServiceProto Clone() {
      return new ServiceProto(this);
    }

    /// <summary>Field number for the "services" field.</summary>
    public const int ServicesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Acorle.Models.ServiceProto.Types.ServiceMessage> _repeated_services_codec
        = pb::FieldCodec.ForMessage(10, global::Acorle.Models.ServiceProto.Types.ServiceMessage.Parser);
    private readonly pbc::RepeatedField<global::Acorle.Models.ServiceProto.Types.ServiceMessage> services_ = new pbc::RepeatedField<global::Acorle.Models.ServiceProto.Types.ServiceMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Acorle.Models.ServiceProto.Types.ServiceMessage> Services {
      get { return services_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServiceProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServiceProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!services_.Equals(other.services_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= services_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      services_.WriteTo(output, _repeated_services_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      services_.WriteTo(ref output, _repeated_services_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += services_.CalculateSize(_repeated_services_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServiceProto other) {
      if (other == null) {
        return;
      }
      services_.Add(other.services_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            services_.AddEntriesFrom(input, _repeated_services_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            services_.AddEntriesFrom(ref input, _repeated_services_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ServiceProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// 子节点业务元素 
      /// </summary>
      public sealed partial class ServiceMessage : pb::IMessage<ServiceMessage>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ServiceMessage> _parser = new pb::MessageParser<ServiceMessage>(() => new ServiceMessage());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ServiceMessage> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Acorle.Models.ServiceProto.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ServiceMessage() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ServiceMessage(ServiceMessage other) : this() {
          hash_ = other.hash_;
          key_ = other.key_;
          name_ = other.name_;
          url_ = other.url_;
          weight_ = other.weight_;
          isPrivate_ = other.isPrivate_;
          addedTimestamp_ = other.addedTimestamp_;
          expireTimestamp_ = other.expireTimestamp_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ServiceMessage Clone() {
          return new ServiceMessage(this);
        }

        /// <summary>Field number for the "hash" field.</summary>
        public const int HashFieldNumber = 1;
        private string hash_ = "";
        /// <summary>
        /// 子节点业务唯一 Hash (在负载均衡有多个相同 key 的情况下标识唯一性） 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Hash {
          get { return hash_; }
          set {
            hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "key" field.</summary>
        public const int KeyFieldNumber = 2;
        private string key_ = "";
        /// <summary>
        /// 子节点业务标识 Key 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Key {
          get { return key_; }
          set {
            key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 3;
        private string name_ = "";
        /// <summary>
        /// 子节点友好名称 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "url" field.</summary>
        public const int UrlFieldNumber = 4;
        private string url_ = "";
        /// <summary>
        /// 子节点所对应的该业务的完整URL 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Url {
          get { return url_; }
          set {
            url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "weight" field.</summary>
        public const int WeightFieldNumber = 5;
        private int weight_;
        /// <summary>
        /// 子节点负载均衡权重 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Weight {
          get { return weight_; }
          set {
            weight_ = value;
          }
        }

        /// <summary>Field number for the "isPrivate" field.</summary>
        public const int IsPrivateFieldNumber = 6;
        private bool isPrivate_;
        /// <summary>
        /// 子节点的服务是是否只对同主体的其他子节点开放，如果为 False，则子节点的业务外网可达 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool IsPrivate {
          get { return isPrivate_; }
          set {
            isPrivate_ = value;
          }
        }

        /// <summary>Field number for the "addedTimestamp" field.</summary>
        public const int AddedTimestampFieldNumber = 7;
        private long addedTimestamp_;
        /// <summary>
        /// JS 时间戳(精确到毫秒) 首次注册的时间 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long AddedTimestamp {
          get { return addedTimestamp_; }
          set {
            addedTimestamp_ = value;
          }
        }

        /// <summary>Field number for the "expireTimestamp" field.</summary>
        public const int ExpireTimestampFieldNumber = 8;
        private long expireTimestamp_;
        /// <summary>
        /// JS 时间戳(精确到毫秒) 过期时间。如果子节点超过规定的时间(regInterval)没有报告自己存活，即此业务暂时不能使用。 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long ExpireTimestamp {
          get { return expireTimestamp_; }
          set {
            expireTimestamp_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ServiceMessage);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ServiceMessage other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Hash != other.Hash) return false;
          if (Key != other.Key) return false;
          if (Name != other.Name) return false;
          if (Url != other.Url) return false;
          if (Weight != other.Weight) return false;
          if (IsPrivate != other.IsPrivate) return false;
          if (AddedTimestamp != other.AddedTimestamp) return false;
          if (ExpireTimestamp != other.ExpireTimestamp) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Hash.Length != 0) hash ^= Hash.GetHashCode();
          if (Key.Length != 0) hash ^= Key.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (Url.Length != 0) hash ^= Url.GetHashCode();
          if (Weight != 0) hash ^= Weight.GetHashCode();
          if (IsPrivate != false) hash ^= IsPrivate.GetHashCode();
          if (AddedTimestamp != 0L) hash ^= AddedTimestamp.GetHashCode();
          if (ExpireTimestamp != 0L) hash ^= ExpireTimestamp.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Hash.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Hash);
          }
          if (Key.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Key);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Name);
          }
          if (Url.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Url);
          }
          if (Weight != 0) {
            output.WriteRawTag(40);
            output.WriteInt32(Weight);
          }
          if (IsPrivate != false) {
            output.WriteRawTag(48);
            output.WriteBool(IsPrivate);
          }
          if (AddedTimestamp != 0L) {
            output.WriteRawTag(56);
            output.WriteInt64(AddedTimestamp);
          }
          if (ExpireTimestamp != 0L) {
            output.WriteRawTag(64);
            output.WriteInt64(ExpireTimestamp);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Hash.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Hash);
          }
          if (Key.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Key);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Name);
          }
          if (Url.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Url);
          }
          if (Weight != 0) {
            output.WriteRawTag(40);
            output.WriteInt32(Weight);
          }
          if (IsPrivate != false) {
            output.WriteRawTag(48);
            output.WriteBool(IsPrivate);
          }
          if (AddedTimestamp != 0L) {
            output.WriteRawTag(56);
            output.WriteInt64(AddedTimestamp);
          }
          if (ExpireTimestamp != 0L) {
            output.WriteRawTag(64);
            output.WriteInt64(ExpireTimestamp);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Hash.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Hash);
          }
          if (Key.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (Url.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
          }
          if (Weight != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Weight);
          }
          if (IsPrivate != false) {
            size += 1 + 1;
          }
          if (AddedTimestamp != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(AddedTimestamp);
          }
          if (ExpireTimestamp != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(ExpireTimestamp);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ServiceMessage other) {
          if (other == null) {
            return;
          }
          if (other.Hash.Length != 0) {
            Hash = other.Hash;
          }
          if (other.Key.Length != 0) {
            Key = other.Key;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.Url.Length != 0) {
            Url = other.Url;
          }
          if (other.Weight != 0) {
            Weight = other.Weight;
          }
          if (other.IsPrivate != false) {
            IsPrivate = other.IsPrivate;
          }
          if (other.AddedTimestamp != 0L) {
            AddedTimestamp = other.AddedTimestamp;
          }
          if (other.ExpireTimestamp != 0L) {
            ExpireTimestamp = other.ExpireTimestamp;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Hash = input.ReadString();
                break;
              }
              case 18: {
                Key = input.ReadString();
                break;
              }
              case 26: {
                Name = input.ReadString();
                break;
              }
              case 34: {
                Url = input.ReadString();
                break;
              }
              case 40: {
                Weight = input.ReadInt32();
                break;
              }
              case 48: {
                IsPrivate = input.ReadBool();
                break;
              }
              case 56: {
                AddedTimestamp = input.ReadInt64();
                break;
              }
              case 64: {
                ExpireTimestamp = input.ReadInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Hash = input.ReadString();
                break;
              }
              case 18: {
                Key = input.ReadString();
                break;
              }
              case 26: {
                Name = input.ReadString();
                break;
              }
              case 34: {
                Url = input.ReadString();
                break;
              }
              case 40: {
                Weight = input.ReadInt32();
                break;
              }
              case 48: {
                IsPrivate = input.ReadBool();
                break;
              }
              case 56: {
                AddedTimestamp = input.ReadInt64();
                break;
              }
              case 64: {
                ExpireTimestamp = input.ReadInt64();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
